language: perl
perl:
  - '5.20.0-thr'              # installs perl 5.20.0 with threading
before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
install:
   - cpanm ExtUtils::MakeMaker
   - cpanm Locale::Msgfmt
   - cpanm --verbose  Module::Install
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
   - cpanm --notest --installdeps .
script:
  - prove -lv $(test-dirs)
