language: perl
perl:
  - '5.14.4-thr'              # installs perl 5.14.4 with threading
before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
install:
   - cpanm ExtUtils::MakeMaker
   - cpanm ExtUtils::Embed
   - cpanm Locale::Msgfmt
   - cpanm Module::Install
   - cpanm --verbose Alien::wxWidgets # Build verbose to keep Travis stimulated
   - cpanm --notest Test::CPAN::Meta     # required by xt/meta.t
   - cpanm --notest Test::MinimumVersion # required by xt/pmv.t
   - cpanm --notest Test::Pod            # required by xt/pod.t
   - cpanm --verbose Wx::Perl::ProcessStream # hacking 5.14.4
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
   - cpanm --notest --installdeps .
script:
  - perl Makefile.PL
  - make
  - prove -bv $(test-dirs)
