language: perl
perl:
  - '5.21.3-thr'              # let's try the current dev. 5.21.3 - threading
  - '5.20.0-thr'              # installs perl 5.20.0 with threading
  - '5.18.2-thr'              # installs perl 5.18.2 with threading
  - '5.16.3-thr'              # installs perl 5.16.3 with threading
  - '5.14.4-thr'              # installs perl 5.14.4 with threading
  - '5.12.5-thr'              # installs perl 5.12.5 with threading
  - '5.10.1-thr'              # installs perl 5.10.1 with threading
before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
install:
   - cpanm ExtUtils::MakeMaker
   - cpanm ExtUtils::Embed
   - cpanm Locale::Msgfmt
   - cpanm Module::Install
   - cpanm --verbose Alien::wxWidgets    # Build verbose to keep Travis stimulated
   - cpanm --notest Test::CPAN::Meta     # required by xt/meta.t
   - cpanm --notest Test::MinimumVersion # required by xt/pmv.t
   - cpanm --notest Test::Pod            # required by xt/pod.t
   - cpanm --notest ExtUtils::ParseXS    # >= 3.16, hacking 5.14.4 & below for Wx
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
   - cpanm --notest --installdeps .
script:
  - perl Makefile.PL
  - make
  - prove -bv $(test-dirs)
